-- Enable necessary extensions for UUID generation
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- /////////////////////////////////////////////////////////////////
-- USER PROFILES (linked 1:1 with auth.users)
-- /////////////////////////////////////////////////////////////////
drop table if exists public.user_profiles cascade;
create table public.user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    avatar_url text,
    notifications_enabled boolean default true,
    timezone text,
    created_at timestamptz default timezone('utc', now()),
    updated_at timestamptz default timezone('utc', now())
);

create or replace function public.handle_user_updated()
returns trigger as $$
begin
    new.updated_at := timezone('utc', now());
    return new;
end;
$$ language plpgsql;

create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row execute procedure public.handle_user_updated();

-- /////////////////////////////////////////////////////////////////
-- SESSIONS (matches existing shape; single source for planned/active/incomplete/complete)
-- /////////////////////////////////////////////////////////////////
drop table if exists public.session_settings cascade;
drop table if exists public.tasks cascade;
drop table if exists public.sessions cascade;

create table public.sessions (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    user_id uuid references auth.users(id) on delete cascade,
    status text not null default 'planned'
        check (status in ('planned', 'active', 'incomplete', 'complete')),
    has_goal boolean not null default false,
    goal text,
    has_tasks boolean not null default false,
    summary text,
    reflection_chat jsonb[],
    completed_at timestamptz,
    title text not null default 'title',
    has_settings boolean not null default false,
    total_time bigint not null default 0,
    time_completed bigint not null default 0
);

create index sessions_user_id_idx on public.sessions(user_id);
create index sessions_created_at_idx on public.sessions(created_at);
create index sessions_status_idx on public.sessions(status);

-- /////////////////////////////////////////////////////////////////
-- TASKS (per-session tasks, referenced by session_id -> sessions.id)
-- /////////////////////////////////////////////////////////////////
create table public.tasks (
    id bigint generated by default as identity primary key,
    session_id bigint not null references public.sessions(id) on delete cascade,
    task_name text not null,
    is_completed boolean not null default false,
    order_index bigint not null,
    time_allotted bigint null,
    time_completed bigint null,
    created_at timestamptz default timezone('utc', now())
);

create index tasks_session_id_idx on public.tasks(session_id);
create index tasks_order_idx on public.tasks(session_id, order_index);

-- /////////////////////////////////////////////////////////////////
-- SESSION SETTINGS (reflection + collaboration controls)
-- /////////////////////////////////////////////////////////////////
create table public.session_settings (
    id uuid primary key default gen_random_uuid(),
    session_id bigint not null references public.sessions(id) on delete cascade,
    user_id uuid references auth.users(id) on delete cascade,
    reflection_reminders boolean default false,
    collab_requests boolean default false,
    collab_friends boolean default false,
    created_at timestamptz default timezone('utc', now())
);

create index session_settings_session_id_idx on public.session_settings(session_id);

-- /////////////////////////////////////////////////////////////////
-- ROW-LEVEL SECURITY
-- /////////////////////////////////////////////////////////////////
alter table public.user_profiles enable row level security;
alter table public.sessions enable row level security;
alter table public.tasks enable row level security;
alter table public.session_settings enable row level security;

create policy "Users can manage own profile" on public.user_profiles
    for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can manage their sessions" on public.sessions
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage tasks for their sessions" on public.tasks
    for all using (
        auth.uid() = (
            select user_id from public.sessions where id = tasks.scheduled_session_id
        )
    ) with check (
        auth.uid() = (
            select user_id from public.sessions where id = tasks.scheduled_session_id
        )
    );

create policy "Users can manage settings for their sessions" on public.session_settings
    for all using (
        auth.uid() = (
            select user_id from public.sessions where id = session_settings.session_id
        )
    ) with check (
        auth.uid() = (
            select user_id from public.sessions where id = session_settings.session_id
        )
    );

-- Notes:
-- - Status supports planned | active | incomplete | complete (incomplete can drive a badge in the client).
-- - Reflection_chat kept as jsonb[] to mirror existing Supabase shape.
-- - total_time is bigint, consistent with current table.
